// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVsSWkGe1yKxtUPm5Kj3QhOMkeR1vREKI',
    appId: '1:704290336700:web:a2259b28ab804b35ac85b9',
    messagingSenderId: '704290336700',
    projectId: 'e-book-app-e8e35',
    authDomain: 'e-book-app-e8e35.firebaseapp.com',
    storageBucket: 'e-book-app-e8e35.firebasestorage.app',
    measurementId: 'G-P38RCM1S7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfjN4NGDX3-FSDIjLb623j3jqJSmFfQsQ',
    appId: '1:704290336700:android:949bdcbe860d3310ac85b9',
    messagingSenderId: '704290336700',
    projectId: 'e-book-app-e8e35',
    storageBucket: 'e-book-app-e8e35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYmXvJkqjzPeg7tumGgiAIJrncKmz6Hrs',
    appId: '1:704290336700:ios:d8bbb52ae86c8cebac85b9',
    messagingSenderId: '704290336700',
    projectId: 'e-book-app-e8e35',
    storageBucket: 'e-book-app-e8e35.firebasestorage.app',
    iosBundleId: 'com.example.myEbookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYmXvJkqjzPeg7tumGgiAIJrncKmz6Hrs',
    appId: '1:704290336700:ios:d8bbb52ae86c8cebac85b9',
    messagingSenderId: '704290336700',
    projectId: 'e-book-app-e8e35',
    storageBucket: 'e-book-app-e8e35.firebasestorage.app',
    iosBundleId: 'com.example.myEbookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVsSWkGe1yKxtUPm5Kj3QhOMkeR1vREKI',
    appId: '1:704290336700:web:8ab16ea7045586a4ac85b9',
    messagingSenderId: '704290336700',
    projectId: 'e-book-app-e8e35',
    authDomain: 'e-book-app-e8e35.firebaseapp.com',
    storageBucket: 'e-book-app-e8e35.firebasestorage.app',
    measurementId: 'G-LX1NX6HSS3',
  );
}
